# Time the data was recorded
time stamp         
# Left encoder data, in ticks
int32 left_encoder 
# Left encoder data, in ticks
int32 right_encoder
# Raw acceleromter x, y, and z data
int16 accelX
int16 accelY
int16 accelZ
# Raw gyroscope x, y, and z data
int16 gyroX
int16 gyroY
int16 gyroZ
# raw magnetometer x, y, and z components
int16 magX
int16 magY
int16 magZ
#battery voltage
float32 battery_voltage
